import app.models.role
import app.models.address
import app.models.user
import app.models.room_type
import app.models.room
import app.models.service
import app.models.invoice
import app.models.reservation
import app.models.association_tables
